spring.application.name=backend_spring

# ↑の一文はプロジェクト作成時にデフォルトである（ここより下が手動で作成するもの）
# PostgreSQL（本来はパスワードを直接書くのはダメ。ローカルなので一旦これでよい。）
spring.datasource.url=jdbc:postgresql://localhost:5432/myapp_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
